name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    uses: oapi-codegen/actions/.github/workflows/ci.yml@a652a33a091fe34e640d44af53fcdf1670d2eded # v0.9.2
    with:
      lint_versions: '["1.26"]'
