name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    uses: oapi-codegen/actions/.github/workflows/ci.yml@8ebfe4c83d051866a4af122ba602239fa3220e52 # v0.7.0
    with:
      lint_versions: '["1.25"]'
